language: node_js
node_js:
  - "0.12"
script: "node . && cd static && bower install && cd .."
before_script: "npm install -g bower"
after_success: |
    mkdir -p target && \
    cp -r static/* target/ && \
    mv generated.json target/ && \
    sudo pip install ghp-import && \
    ghp-import -n target && \
    git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
